# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/ratatui/first" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/ratatui/second" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/ratatui/widget1" # Location of package manifests
    schedule:
      interval: "weekly"
