name = "Leibniz"
defaultTargets = ["leibniz"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
# version = "git#29f9a66d622d9bab7f419120e22bb0d2598676ab"
tag = "v4.16.0"

[[require]]
name = "aesop"
scope = "leanprover-community"
# version = "git#2689851f387bb2cef351e6825fe94a56a304ca13"
tag = "v4.16.0"

[[lean_lib]]
name = "Combinator"

[[lean_lib]]
name = "Math"

[[lean_lib]]
name = "Misc"

[[lean_lib]]
name = "old"

[[lean_exe]]
name = "leibniz"
root = "Main"
