name = "Le"
defaultTargets = ["le"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Le"

[[lean_lib]]
name = "Combinator"

[[lean_exe]]
name = "le"
root = "Main"
