name = "Leibniz"
defaultTargets = ["leibniz"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "aesop"
scope = "leanprover-community"
tag = "v4.14.0"

[[lean_lib]]
name = "Combinator"

[[lean_lib]]
name = "Leibniz"

[[lean_lib]]
name = "Misc"

[[lean_exe]]
name = "leibniz"
root = "Main"
