name = "Leibniz"
defaultTargets = ["leibniz"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.18.0-rc1"

[[require]]
name = "aesop"
scope = "leanprover-community"
rev = "v4.18.0-rc1"

[[lean_lib]]
name = "Combinator"

[[lean_lib]]
name = "Math"

[[lean_lib]]
name = "Misc"

[[lean_lib]]
name = "Program"

[[lean_lib]]
name = "old"

[[lean_exe]]
name = "leibniz"
root = "Main"
